name: Python CI/CD with Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt pytest

      - name: Run tests
        run: PYTHONPATH=. pytest -v   # 👈 Fix: add PYTHONPATH

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: abhishekmandal/python-docker-actions:latest


  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull abhishekmandal/my-python-app:latest
            echo "Stopping old container (if any)..."
            docker stop myapp || true
            docker rm myapp || true
            echo "Starting new container..."
            docker run -d --name myapp -p 80:8000 abhishekmandal/my-python-app:latest
